name: notify

on:
  issues:
    types:
      - opened
      - deleted
      - closed
      - reopened
      - assigned
      - unassigned
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
  pull_request_review:
    types:
      - submitted

jobs:
  notify:
    uses: dato/github.common/.github/workflows/notifications.yaml@main
    secrets:
      password: ${{ secrets.IRC_PASSWORD }}
